# Generated by Django 5.0.4 on 2024-05-04 05:22

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_created_by_lesson_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, validators=[courses.validators.validate_link]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, validators=[courses.validators.validate_link]),
        ),
    ]
